language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t nileshb83/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nileshb83/react-test npm test -- --coverage

after_success:
    - docker build -t nileshb83/multi-client ./client
    - docker build -t nileshb83/multi-nginx ./nginx
    - docker build -t nileshb83/multi-server ./server
    - docker build -t nileshb83/multi-worker ./worker
    # login in Docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push Images
    - docker push nileshb83/multi-client
    - docker push nileshb83/multi-nginx
    - docker push nileshb83/multi-server
    - docker push nileshb83/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "multi-docker"
    env : "MultiDocker-env"
    bucket_name: "elasticbeanstalk-eu-west-2-679645747196"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY